-- Migration 003: This migration is now a no-op since the base schema doesn't have comparison column
-- Keeping file for migration history purposes
-- The schema.sql already creates alert_rules with the correct structure
