-- Migration 004: This migration is now a no-op since the base schema already has the correct structure
-- The schema.sql already creates alert_rules without the comparison column
-- Keeping file for migration history purposes
